sudo: required
language: python
python: '3.6'
services:
  - docker
stages:
  - name: deploy
    if: tag =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
jobs:
  include:
    - stage: deploy
      script:
        - sed -i "s/VERSION.*=.*/VERSION = '${TRAVIS_TAG}'/g" fandogh_cli/__init__.py
      deploy:
        - provider: script
          script: docker build -t fandoghpaas/fandogh-cli .;echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin; docker push fandoghpaas/fandogh-cli:latest
          skip_cleanup: true
          on:
            all_branches: true
        - provider: script
          script: docker build -t fandoghpaas/fandogh-cli:${TRAVIS_TAG} .;echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin; docker push fandoghpaas/fandogh-cli:${TRAVIS_TAG}
          skip_cleanup: true
          on:
            all_branches: true
        - provider: pypi
          user: ${PYPI_USERNAME}
          password: ${PYPI_PASSWORD}
          skip_cleanup: true
          skip_existing: true
          on:
            all_branches: true
